spring.application.name=chat-app

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp3
spring.datasource.username=smart
spring.datasource.password=password
spring.flyway.baselineOnMigrate=true
