spring.application.name=chat-app

# データベースに接続するための記述
]spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username= smart
spring.datasource.password= password

# Flywayの設定
spring.flyway.baselineOnMigrate=true